import sys
sys.path.insert(0, '../')
import numpy as np
from discrete_distr import DiscreteDistr
from markov_chain import MarkovChain

def main():
	q1 = np.array([0.5, 0.5])
	A1 = np.array([[0.9, 0.1], [0.05, 0.95]])
	mc1 = MarkovChain(q1, A1)
	x1 = mc1.rand(100)
	print "state sequence generated by a infinite-duration MC:"
	print x1

	q2 = np.array([0.25, 0.25, 0.25, 0.25])
	A2 = np.array([[0.3,0.2,0.1,0.1,0.3],
		          [0.1,0.7,0.1,0,0.1],
		          [0.3,0.2,0.1,0.1,0.3],
		          [0.8,0.1,0.05,0.04,0.01]]);
	mc2 = MarkovChain(q2, A2)
	x2 = mc2.rand(100)
	print "state sequence generated by a finite-duration MC:"
	print x2


if __name__ == "__main__":
	main()